version: '3.4'

services:
  apache:
    image: 'httpd:2.4'
    container_name: alduxino_apache2
    restart: always
    ports:
        - '80:80'
    volumes:
        - './www:/usr/local/apache2/htdocs/'
